//! TS-S3 end to end: compiler-derived Angular evidence (`adapters/angular-evidence/fixtures/*`,
//! generated by the pinned adapter; CI re-derives them) ingested against the real tree-sitter
//! index of the same sources.

use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::{Value, json};
use wicked_estate::ingest_semantic_evidence;
use wicked_estate_core::evidence::{EvidenceSkip, SemanticEvidence};
use wicked_estate_core::{
    Edge, FlowEvidence, GraphRead, Node, NodeKind, Provenance, RetrievalTool, field_slot_id,
    flow_evidence_of, is_flow_edge,
};
use wicked_estate_store::SqliteStore;

const FIXTURES: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../adapters/angular-evidence/fixtures"
);

fn copy_dir(from: &Path, to: &Path) {
    fs::create_dir_all(to).unwrap();
    for e in fs::read_dir(from).unwrap() {
        let e = e.unwrap();
        let p = e.path();
        let name = e.file_name();
        if name == "evidence.json" || name == "node_modules" {
            continue;
        }
        if p.is_dir() {
            copy_dir(&p, &to.join(&name));
        } else {
            fs::copy(&p, to.join(&name)).unwrap();
        }
    }
}

/// Index a fixture's sources; return the scratch root, the store and the committed envelope.
fn indexed(case: &str, tag: &str) -> (PathBuf, SqliteStore, SemanticEvidence) {
    let src = Path::new(FIXTURES).join(case);
    let root = std::env::temp_dir().join(format!("ci_angular_{case}_{tag}_{}", std::process::id()));
    let _ = fs::remove_dir_all(&root);
    copy_dir(&src, &root);
    let mut store = SqliteStore::open(root.join(".g.db")).unwrap();
    wicked_estate::index_path(&mut store, &root).unwrap();
    let ev = serde_json::from_str(&fs::read_to_string(src.join("evidence.json")).unwrap()).unwrap();
    (root, store, ev)
}

fn class(store: &SqliteStore, file: &str, name: &str) -> Node {
    let found: Vec<Node> = store
        .all_nodes()
        .unwrap()
        .into_iter()
        .filter(|n| n.kind == NodeKind::Class && n.name == name && n.location.file == file)
        .collect();
    assert_eq!(found.len(), 1, "{file}#{name}: {found:?}");
    found.into_iter().next().unwrap()
}

fn compiler_flows(store: &SqliteStore) -> Vec<Edge> {
    store
        .all_edges()
        .unwrap()
        .into_iter()
        .filter(|e| is_flow_edge(e) && e.resolved_by == "angular-compiler-adapter")
        .collect()
}

#[test]
fn compiler_resolved_inputs_project_between_canonical_field_slots() {
    let (root, mut store, ev) = indexed("bindings", "t1");
    let report = ingest_semantic_evidence(&mut store, Some(&root), &ev, None).unwrap();

    let child = class(&store, "src/child.ts", "Child");
    let other = class(&store, "src/other/child.ts", "Child");
    let base = class(&store, "src/child.ts", "Base");
    let parent = class(&store, "src/parent.ts", "Parent");
    let ext = class(&store, "src/ext.component.ts", "Ext");
    let review = class(&store, "src/review.ts", "Review");
    let my_if = class(&store, "src/review.ts", "MyIf");
    let badge = class(&store, "src/review.ts", "Badge");
    let ns = class(&store, "src/review.ts", "NsCmp");
    let alias = class(&store, "src/review.ts", "AliasCmp");
    let flag = class(&store, "src/review.ts", "Flag");
    let order = class(&store, "src/review.ts", "Order");
    let hd = class(&store, "src/review.ts", "Hd");
    let quoted = class(&store, "src/review.ts", "Quoted");
    let r3 = class(&store, "src/review.ts", "R3");
    let slot = |c: &Node, f: &str| field_slot_id(&c.symbol, f);

    // Stored consumer → producer, one public edge per (input slot, host slot).
    let keys: BTreeSet<(String, String)> = compiler_flows(&store)
        .into_iter()
        .filter(|e| e.metadata.get("evidence_fact") == Some(&json!("input_binding")))
        .map(|e| (e.source.0, e.target.0))
        .collect();
    let want: BTreeSet<(String, String)> = [
        (slot(&child, "user"), slot(&parent, "current")),
        (slot(&child, "renamed"), slot(&parent, "count")), // alias `aliasIn`
        (slot(&child, "name"), slot(&parent, "label")),    // signal input
        (slot(&child, "value"), slot(&parent, "v")),       // two-way input half
        (slot(&child, "user"), slot(&parent, "label")),    // through a pipe
        (slot(&other, "user"), slot(&parent, "other")),    // same class name, other file
        (slot(&other, "user"), slot(&parent, "current")),  // Unicode line
        (slot(&child, "user"), slot(&ext, "title")),       // templateUrl
        (slot(&child, "user"), slot(&review, "current")),  // `this.current`
        (slot(&my_if, "myIf"), slot(&review, "current")),  // structural `*myIf`
        (slot(&child, "value"), slot(&review, "nums")),    // keyed two-way `nums[idx]`
        (slot(&child, "value"), slot(&review, "idx")),
        (slot(&badge, "badge"), slot(&review, "computed")), // setter input ← getter
        (slot(&child, "user"), slot(&ns, "nsField")),       // `@ng.Component`
        (slot(&child, "user"), slot(&alias, "aliasField")), // `@Cmp` (renamed import)
        (slot(&flag, "enabled"), slot(&order, "text")),     // decorator input with transform
        (slot(&flag, "on"), slot(&order, "text")),          // signal input with transform
        (slot(&child, "user"), slot(&order, "ordered")),    // setter declared before getter
        (slot(&hd, "raw"), slot(&r3, "field")),             // host directive, exposed as `renamed`
        (slot(&quoted, "q"), slot(&r3, "field")),           // quoted `transform` key
    ]
    .into_iter()
    .map(|(a, b)| (a.0, b.0))
    .collect();
    assert_eq!(keys, want, "{report:?}");
    let _ = base; // inherited `[inherited]="'x'"` binds a literal: nothing to project

    for e in compiler_flows(&store) {
        assert_eq!(e.provenance, Provenance::Compiler);
        assert_eq!(
            flow_evidence_of(&e).into_iter().collect::<Vec<_>>(),
            vec![FlowEvidence::Compiler]
        );
    }
    // Every binding the adapter could not resolve is counted, never guessed.
    // 4 input reads (template locals, a pipe) + TS-S4: a keyed two-way target, a `@let` handler
    // shadowing a host method, and both halves of a two-way binding to a `@let` local.
    assert_eq!(report.skipped.get(&EvidenceSkip::UnresolvedRead), Some(&8));
    let ev_host3 = class(&store, "src/events.ts", "EvHost3");
    assert!(
        compiler_flows(&store)
            .iter()
            .all(|e| e.source != field_slot_id(&ev_host3.symbol, "mine")
                && e.target != field_slot_id(&ev_host3.symbol, "mine")),
        "a `@let mine` must not resolve to the shadowed host field"
    );
    assert_eq!(
        report.flows_projected,
        21 + 11, // 21 input-binding flows + 11 TS-S4 event payload flows
        "current→user is asserted at two sites"
    );
    assert_eq!(
        report.skipped.get(&EvidenceSkip::UnknownSlot),
        None,
        "{report:?}"
    );
    // A keyed two-way binding reads `nums` and `idx`, and a transformed input coerces its value:
    // neither preserves the producer's whole value.
    for (c, p) in [
        (slot(&child, "value"), slot(&review, "nums")),
        (slot(&flag, "enabled"), slot(&order, "text")),
        (slot(&flag, "on"), slot(&order, "text")),
        (slot(&quoted, "q"), slot(&r3, "field")),
    ] {
        let e = compiler_flows(&store)
            .into_iter()
            .find(|e| e.source == c && e.target == p)
            .unwrap();
        assert_eq!(
            wicked_estate_core::flow_semantics_of(&e)
                .into_iter()
                .collect::<Vec<_>>(),
            vec![wicked_estate_core::FlowSemantics::MayInfluence],
            "{c:?} <- {p:?}"
        );
    }

    // UTF-16 columns from the compiler are stored as UTF-8 byte columns: `🙂` and `ü` widen.
    let rows = store
        .edge_supports(
            &slot(&other, "user"),
            &slot(&parent, "current"),
            &wicked_estate_core::edge_tags::other(wicked_estate_core::edge_tags::FLOWS_TO),
        )
        .unwrap();
    let loc = rows[0].fact.location.clone().unwrap();
    let line = fs::read_to_string(root.join("src/parent.ts"))
        .unwrap()
        .lines()
        .nth(loc.span.start_line as usize)
        .unwrap()
        .to_string();
    assert_eq!(
        &line[loc.span.start_col as usize..loc.span.end_col as usize],
        "user"
    );

    // The tree-sitter convention edge for `@Input() user` coexists under its own key.
    assert!(
        store.all_edges().unwrap().iter().any(|e| is_flow_edge(e)
            && e.source == slot(&child, "user")
            && e.resolved_by == "tree-sitter-convention"),
        "convention edge must survive"
    );
    let _ = fs::remove_dir_all(root);
}

/// #215 end to end: a template input reaches the child field, and the field's `this.user` read
/// inside `Child.shout()`, as one forward Lineage chain.
#[test]
fn a_template_input_continues_through_the_component_field_read() {
    let (root, mut store, ev) = indexed("bindings", "t2");
    ingest_semantic_evidence(&mut store, Some(&root), &ev, None).unwrap();
    let child = class(&store, "src/child.ts", "Child");
    let parent = class(&store, "src/parent.ts", "Parent");
    let start = field_slot_id(&parent.symbol, "current");
    let r = wicked_estate_retrieve::Lineage
        .invoke(
            &store,
            &json!({"symbol": start.0, "relation": "flows_to", "depth": 6}),
        )
        .unwrap();
    let hops: Vec<(String, String)> = r.content["flows"]
        .as_array()
        .unwrap()
        .iter()
        .map(|h: &Value| {
            (
                h["producer"].as_str().unwrap().to_string(),
                h["consumer"].as_str().unwrap().to_string(),
            )
        })
        .collect();
    let user = field_slot_id(&child.symbol, "user").0;
    assert!(
        hops.contains(&(start.0.clone(), user.clone())),
        "compiler hop missing: {hops:?}"
    );
    assert!(
        hops.iter()
            .any(|(p, c)| p == &user && c.contains(":local:loud")),
        "the field read must continue the chain: {hops:?}"
    );
    let _ = fs::remove_dir_all(root);
}

#[test]
fn replacement_isolation_and_empty_snapshots_hold_for_compiler_bindings() {
    let (root, mut store, ev) = indexed("bindings", "t3");
    ingest_semantic_evidence(&mut store, Some(&root), &ev, None).unwrap();
    let before = compiler_flows(&store);
    // A second snapshot (another tsconfig asserting the same bindings) supports the same edges.
    let second = SemanticEvidence {
        snapshot: "fixtures/bindings-spec".into(),
        ..ev.clone()
    };
    ingest_semantic_evidence(&mut store, Some(&root), &second, None).unwrap();
    assert_eq!(compiler_flows(&store), before);
    // Emptying the first leaves every edge supported by the second.
    let empty = SemanticEvidence {
        facts: vec![],
        documents: vec![],
        ..ev.clone()
    };
    let r = ingest_semantic_evidence(&mut store, Some(&root), &empty, None).unwrap();
    assert_eq!(r.generation, Some(2));
    assert_eq!(compiler_flows(&store), before);
    // Emptying the second retracts them; the base plane's convention flows remain.
    let empty2 = SemanticEvidence {
        facts: vec![],
        documents: vec![],
        ..second
    };
    ingest_semantic_evidence(&mut store, Some(&root), &empty2, None).unwrap();
    assert!(compiler_flows(&store).is_empty());
    assert!(
        store
            .all_edges()
            .unwrap()
            .iter()
            .any(|e| is_flow_edge(e) && e.resolved_by == "tree-sitter-convention")
    );
    // Replaying an older generation is refused.
    let stale = SemanticEvidence {
        generation: Some(1),
        ..ev
    };
    assert!(ingest_semantic_evidence(&mut store, Some(&root), &stale, None).is_err());
    let _ = fs::remove_dir_all(root);
}

#[test]
fn a_partial_build_projects_only_what_the_compiler_resolved() {
    let (root, mut store, ev) = indexed("partial", "t4");
    let r = ingest_semantic_evidence(&mut store, Some(&root), &ev, None).unwrap();
    assert_eq!(r.flows_projected, 1, "{r:?}");
    assert_eq!(r.skipped.get(&EvidenceSkip::UnresolvedRead), Some(&1));
    let leaf = class(&store, "src/app.ts", "Leaf");
    let rootc = class(&store, "src/app.ts", "Root");
    let keys: Vec<(String, String)> = compiler_flows(&store)
        .into_iter()
        .map(|e| (e.source.0, e.target.0))
        .collect();
    assert_eq!(
        keys,
        vec![(
            field_slot_id(&leaf.symbol, "user").0,
            field_slot_id(&rootc.symbol, "name").0
        )]
    );
    let _ = fs::remove_dir_all(root);
}

/// `wicked-estate evidence <envelope.json>`: the CLI face of `ingest_semantic_evidence`.
#[test]
fn the_evidence_cli_ingests_an_envelope_and_refuses_bad_input() {
    let (root, store, _) = indexed("partial", "cli");
    drop(store);
    let envelope = Path::new(FIXTURES).join("partial/evidence.json");
    let run = |args: &[&str]| {
        std::process::Command::new(env!("CARGO_BIN_EXE_wicked-estate"))
            .current_dir(&root)
            .args(args)
            .env_remove("WICKED_ESTATE_DB")
            .env_remove("WICKED_STORE_URL")
            .env_remove("WICKED_RUNTIME")
            .output()
            .unwrap()
    };
    let env_s = envelope.to_str().unwrap();
    let out = run(&["evidence", env_s, "--root", ".", "--json", "--db", ".g.db"]);
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let report: Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(report["flows_projected"], json!(1), "{report}");
    assert_eq!(report["generation"], json!(1));

    // An envelope this build cannot read is refused, and the graph is not touched.
    let bad = root.join("bad.json");
    let mut doc: Value = serde_json::from_str(&fs::read_to_string(&envelope).unwrap()).unwrap();
    doc["schema_version"] = json!(2);
    fs::write(&bad, doc.to_string()).unwrap();
    let before = fs::read(root.join(".g.db")).unwrap();
    let out = run(&["evidence", bad.to_str().unwrap(), "--db", ".g.db"]);
    assert!(!out.status.success());
    assert!(String::from_utf8_lossy(&out.stderr).contains("schema_version 2"));
    assert_eq!(
        fs::read(root.join(".g.db")).unwrap(),
        before,
        "an invalid envelope must not touch the graph (no open, no migration)"
    );
    // Without --root the graph's recorded root is used, so text mode reports zero unconverted.
    let out = run(&["evidence", env_s, "--db", ".g.db"]);
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(
        String::from_utf8_lossy(&out.stdout).contains("0 position(s) unconverted"),
        "{}",
        String::from_utf8_lossy(&out.stdout)
    );

    // A missing graph is refused and never created.
    let out = run(&["evidence", env_s, "--db", "missing.db"]);
    assert!(!out.status.success());
    assert!(!root.join("missing.db").exists());
    let _ = fs::remove_dir_all(root);
}

fn method(store: &SqliteStore, file: &str, class_name: &str, name: &str) -> Node {
    let owner = class(store, file, class_name);
    let found: Vec<Node> = store
        .all_nodes()
        .unwrap()
        .into_iter()
        .filter(|n| {
            n.kind == NodeKind::Method
                && n.name == name
                && n.location.file == file
                && n.location.span.start_line >= owner.location.span.start_line
                && n.location.span.end_line <= owner.location.span.end_line
        })
        .collect();
    assert_eq!(found.len(), 1, "{class_name}.{name}: {found:?}");
    found.into_iter().next().unwrap()
}

/// TS-S4: template events deliver to handlers (`event-listens`, never `Calls`) and carry `$event`
/// as compiler-evidence `flows_to` from the output's field slot (the payload producer).
#[test]
fn template_events_listen_and_carry_their_payload() {
    use wicked_estate_core::param_slot_id;
    let (root, mut store, ev) = indexed("bindings", "events");
    let report = ingest_semantic_evidence(&mut store, Some(&root), &ev, None).unwrap();
    let f = "src/events.ts";
    let child = class(&store, f, "EvChild");
    let base = class(&store, f, "EvBase");
    let host = class(&store, f, "EvHost");
    let (ping_a, ping_b, clicky) = (
        class(&store, f, "PingA"),
        class(&store, f, "PingB"),
        class(&store, f, "Clicky"),
    );
    let on_pick = method(&store, f, "EvHost", "onPick");
    let on_pick2 = method(&store, f, "EvHost2", "onPick");
    let done = method(&store, f, "EvHost", "done");
    let pinged = method(&store, f, "EvHost", "pinged");
    let slot = |c: &Node, m: &str| field_slot_id(&c.symbol, m).0;

    let listens: BTreeSet<(String, String)> = store
        .all_edges()
        .unwrap()
        .into_iter()
        .filter(|e| {
            e.kind
                == wicked_estate_core::edge_tags::other(
                    wicked_estate_core::edge_tags::EVENT_LISTENS,
                )
        })
        .map(|e| (e.source.0, e.target.0))
        .collect();
    let want: BTreeSet<(String, String)> = [
        (on_pick.symbol.0.clone(), slot(&child, "picked")),
        (done.symbol.0.clone(), slot(&child, "closed")), // signal output, chained handler
        (on_pick.symbol.0.clone(), slot(&base, "baseEv")), // inherited output
        (pinged.symbol.0.clone(), slot(&ping_a, "ping")), // two directives, one name
        (pinged.symbol.0.clone(), slot(&ping_b, "ping")),
        (on_pick.symbol.0.clone(), slot(&clicky, "click")), // an output named like a DOM event
        (on_pick2.symbol.0.clone(), slot(&child, "picked")), // same handler name, other host
        (
            method(&store, f, "EvHost3", "withThis").symbol.0,
            slot(&child, "picked"),
        ),
    ]
    .into_iter()
    .collect();
    assert_eq!(listens, want, "{report:?}");
    // A `@let pick` shadows `EvHost3.pick`: no listener is invented for the host method.
    let pick = method(&store, f, "EvHost3", "pick");
    assert!(
        !listens.iter().any(|(src, _)| src == &pick.symbol.0),
        "a template-local handler must not resolve to the host method"
    );
    // The DOM `(click)` projects nothing; no template event ever becomes a call.
    assert_eq!(report.skipped.get(&EvidenceSkip::DomEvent), Some(&1));
    assert!(
        store
            .all_edges()
            .unwrap()
            .iter()
            .all(|e| !(e.kind == wicked_estate_core::EdgeKind::Calls
                && e.resolved_by == "angular-compiler-adapter"))
    );

    let flows: BTreeSet<(String, String)> = compiler_flows(&store)
        .into_iter()
        .filter(|e| e.target.0.contains("src/events/") || e.source.0.contains("src/events/"))
        .map(|e| (e.source.0, e.target.0))
        .collect();
    for pair in [
        (
            param_slot_id(&on_pick.symbol, "value").0,
            slot(&child, "picked"),
        ),
        (slot(&host, "n"), slot(&child, "changed")), // alias `renamedOut`, `n = $event`
        (
            param_slot_id(&on_pick.symbol, "value").0,
            slot(&base, "baseEv"),
        ),
        (param_slot_id(&pinged.symbol, "p").0, slot(&ping_a, "ping")),
        (param_slot_id(&pinged.symbol, "p").0, slot(&ping_b, "ping")),
        (slot(&host, "last"), slot(&child, "picked")),
        (
            param_slot_id(&on_pick2.symbol, "other").0,
            slot(&child, "picked"),
        ),
        // `withThis(this: EvHost3, value, n)`: the type-only `this` takes no argument position.
        (
            param_slot_id(&method(&store, f, "EvHost3", "withThis").symbol, "value").0,
            slot(&child, "picked"),
        ),
    ] {
        assert!(
            flows.contains(&pair),
            "missing payload flow {pair:?} in {flows:?}"
        );
    }
    // `$event.trim()` is derived: it influences, it does not preserve.
    let derived = compiler_flows(&store)
        .into_iter()
        .find(|e| {
            e.source == param_slot_id(&on_pick.symbol, "value")
                && e.target.0 == slot(&base, "baseEv")
        })
        .unwrap();
    assert_eq!(
        wicked_estate_core::flow_semantics_of(&derived)
            .into_iter()
            .collect::<Vec<_>>(),
        vec![wicked_estate_core::FlowSemantics::MayInfluence]
    );

    // Two-way output half: the host field receives the child's model, the reverse key of the
    // input half (which stays as it was).
    let parent = class(&store, "src/parent.ts", "Parent");
    let model = class(&store, "src/child.ts", "Child");
    let keys: BTreeSet<(String, String)> = compiler_flows(&store)
        .into_iter()
        .map(|e| (e.source.0, e.target.0))
        .collect();
    assert!(keys.contains(&(slot(&parent, "v"), slot(&model, "value"))));
    assert!(keys.contains(&(slot(&model, "value"), slot(&parent, "v"))));
    let _ = fs::remove_dir_all(root);
}

/// Deleting a template's file does not retract producer support located in it; the next
/// snapshot does.
#[test]
fn file_deletion_alone_does_not_retract_event_support() {
    let (root, mut store, ev) = indexed("bindings", "events_delete");
    ingest_semantic_evidence(&mut store, Some(&root), &ev, None).unwrap();
    let ext = class(&store, "src/ext.component.ts", "Ext");
    let child = class(&store, "src/events.ts", "EvChild");
    let consumer = field_slot_id(&ext.symbol, "title");
    let producer = field_slot_id(&child.symbol, "picked");
    let flows = wicked_estate_core::edge_tags::other(wicked_estate_core::edge_tags::FLOWS_TO);
    let rows = |s: &SqliteStore| s.edge_supports(&consumer, &producer, &flows).unwrap();
    let before = rows(&store);
    assert_eq!(before.len(), 1);
    assert_eq!(
        before[0].fact.location.as_ref().unwrap().file,
        "src/ext.component.html",
        "the support under test is located in the file we delete"
    );
    fs::remove_file(root.join("src/ext.component.html")).unwrap();
    wicked_estate::index_path(&mut store, &root).unwrap();
    assert_eq!(
        rows(&store),
        before,
        "a file deletion is not a producer retraction"
    );
    let empty = SemanticEvidence {
        facts: vec![],
        documents: vec![],
        ..ev
    };
    ingest_semantic_evidence(&mut store, Some(&root), &empty, None).unwrap();
    assert!(rows(&store).is_empty());
    let _ = fs::remove_dir_all(root);
}
