#!/usr/bin/env python3
"""Generate crates/wicked-estate-extract/languages.toml from a tree-sitter `.scm` query-file set.

One-time/refresh import: classifies each language's declared extraction capabilities from the
capture families present in its `.scm` file — the code-driven capability matrix prior art asked
for (their) but never built. Parity target: every language prior art ships.

Usage:
    python3 scripts/gen-language-manifest.py [SEARCH_QUERIES_DIR]
default SEARCH_QUERIES_DIR = ~/Projects/prior art/packages/backend/scripts/search_queries
"""
import os, re, sys, glob

SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser(
    "~/Projects/prior art/packages/backend/scripts/search_queries")
OUT = os.path.join(os.path.dirname(__file__), "..", "crates", "wicked-estate-extract", "languages.toml")

# Languages that are config/markup — indexed as documents, not code (per the matrix).
DOCUMENT = {
    "markdown", "yaml", "html", "sql", "dockerfile", "toml", "properties", "xml", "vue",
    "svelte", "make", "graphql", "proto", "hcl", "rego", "verilog", "vhdl", "nix", "cmake",
    "udev", "chatito", "sparql", "generic",
}
# Best-effort file extensions for routing (filled progressively; empty = TODO at W2.1).
EXT = {
    "ada": ["adb", "ads"], "apex": ["cls", "trigger"], "arduino": ["ino"], "asm": ["asm", "s"],
    "bash": ["sh", "bash"], "c": ["c", "h"], "clojure": ["clj", "cljs", "cljc"],
    "cmake": ["cmake"], "commonlisp": ["lisp", "cl"], "cpp": ["cpp", "cc", "cxx", "hpp", "hh"],
    "csharp": ["cs"], "cuda": ["cu", "cuh"], "d": ["d"], "dart": ["dart"],
    "dockerfile": ["dockerfile"], "elisp": ["el"], "elixir": ["ex", "exs"], "elm": ["elm"],
    "erlang": ["erl", "hrl"], "fish": ["fish"], "fortran": ["f90", "f95", "f"],
    "fsharp": ["fs", "fsi", "fsx"], "go": ["go"], "graphql": ["graphql", "gql"],
    "groovy": ["groovy", "gradle"], "haskell": ["hs"], "hcl": ["tf", "hcl"], "html": ["html", "htm"],
    "java": ["java"], "javascript": ["js", "jsx", "mjs", "cjs"], "json": ["json"], "julia": ["jl"],
    "kotlin": ["kt", "kts"], "lua": ["lua"], "make": ["mk", "makefile"], "markdown": ["md", "markdown"],
    "matlab": ["m"], "nim": ["nim"], "nix": ["nix"], "objc": ["m", "mm"], "ocaml": ["ml"],
    "ocaml_interface": ["mli"], "perl": ["pl", "pm"], "php": ["php"], "pony": ["pony"],
    "powershell": ["ps1", "psm1"], "properties": ["properties"], "proto": ["proto"],
    "python": ["py", "pyi"], "r": ["r"], "racket": ["rkt"], "rego": ["rego"], "ruby": ["rb"],
    "rust": ["rs"], "scala": ["scala", "sc"], "solidity": ["sol"], "sparql": ["rq"],
    "sql": ["sql"], "starlark": ["bzl", "star"], "svelte": ["svelte"], "swift": ["swift"],
    "thrift": ["thrift"], "toml": ["toml"], "tsx": ["tsx"], "typescript": ["ts"],
    "udev": ["rules"], "verilog": ["v", "sv"], "vhdl": ["vhd", "vhdl"], "vue": ["vue"],
    "xml": ["xml"], "yaml": ["yaml", "yml"], "zig": ["zig"],
}


def classify(name, text):
    has_cap = "@" in text
    calls = bool(re.search(r"@call|call\.function|call\.method", text))
    imports = "@import" in text or re.search(r"\bimport\b", text) is not None
    extends = "code_extends" in text
    implements = "code_implements" in text
    caps = []
    if has_cap:
        caps.append("symbols")
    if calls:
        caps.append("calls")
    if imports:
        caps.append("imports")
    if extends:
        caps.append("extends")
    if implements:
        caps.append("implements")
    if name in DOCUMENT:
        tier = "document"
    elif calls and imports:
        tier = "structural"
    elif has_cap:
        tier = "tags"
    else:
        tier = "detected"
    return tier, caps


def main():
    files = sorted(glob.glob(os.path.join(SRC, "*.scm")))
    if not files:
        sys.exit(f"no .scm files under {SRC}")
    rows = []
    for f in files:
        name = os.path.basename(f)[:-4]
        text = open(f, encoding="utf-8", errors="ignore").read()
        tier, caps = classify(name, text)
        ext = EXT.get(name, [])
        rows.append((name, ext, f"tree-sitter-{name}", tier, caps))

    lines = [
        "# wicked_estate language manifest — GENERATED by scripts/gen-language-manifest.py.",
        "# Parity target: every language prior art ships (tree-sitter .scm set).",
        "# `tier` = document | detected | tags | structural | precise.",
        "#   tags = symbols only · structural = +calls/imports/heritage (tree-sitter) ·",
        "#   precise = extends/implements + cross-file refs delivered by the SCIP/TSG/LSP",
        "#   resolution tiers, NOT by tree-sitter (that's how we beat the matrix).",
        "# ADD A LANGUAGE WITHOUT SURGERY: add a row here + a <name>.scm query file. No core code.",
        f"# {len(rows)} languages.",
        "",
    ]
    for name, ext, grammar, tier, caps in rows:
        ext_s = ", ".join(f'"{e}"' for e in ext)
        caps_s = ", ".join(f'"{c}"' for c in caps)
        lines.append("[[language]]")
        lines.append(f'name = "{name}"')
        lines.append(f"ext = [{ext_s}]")
        lines.append(f'grammar = "{grammar}"')
        lines.append(f'tier = "{tier}"')
        lines.append(f"caps = [{caps_s}]")
        lines.append("")

    with open(os.path.normpath(OUT), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {os.path.normpath(OUT)} — {len(rows)} languages")


if __name__ == "__main__":
    main()
